In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
l = [2, 6, 7, 3, 4, 9, 2, 1]

In [6]:
arr = np.array(l)

In [7]:
arr

array([2, 6, 7, 3, 4, 9, 2, 1])

In [8]:
arr[1:4]

array([6, 7, 3])

In [9]:
type(arr)

numpy.ndarray

In [10]:
l_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
arr2d = np.array(l_2d)

In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [17]:
np.zeros(3)
#these zeroes are floating point numbers hence, the0. value instead of 0

array([0., 0., 0.])

In [19]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.ones((5,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
zeros = np.zeros((5,4,3))

In [26]:
zeros[1,3,2] = 99

In [27]:
zeros

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0., 99.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [30]:
 ones = np.ones((5,4))    

In [35]:
ones *4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [37]:
ones * 4 - 6

array([[-2., -2., -2., -2.],
       [-2., -2., -2., -2.],
       [-2., -2., -2., -2.],
       [-2., -2., -2., -2.],
       [-2., -2., -2., -2.]])

In [40]:
np.linspace(0, 100, 50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [41]:
ones.shape

(5, 4)

In [42]:
ones[4,1]=99

In [43]:
ones

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1., 99.,  1.,  1.]])

In [44]:
ones.T

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 99.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [45]:
ones.reshape(4,5)
#for no loss of data, make sure the x1*y1 is equal to x2*y2

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., 99.,  1.,  1.]])

In [46]:
ones.flatten()
#Flattening the data

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1., 99.,  1.,  1.])

In [48]:
ones.reshape(2,2,5)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1., 99.,  1.,  1.]]])

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.sqrt(64)

8.0

In [51]:
ones

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1., 99.,  1.,  1.]])

In [52]:
ones.mean()
#mean of whole matrix ones

5.9

In [53]:
ones.mean(axis=0)
#columnwise mean of ones

array([ 1. , 20.6,  1. ,  1. ])

In [59]:
ones.mean(axis=1)
#rowwise mean of matrix ones

array([ 1. ,  1. ,  1. ,  1. , 25.5])

In [56]:
arr = np.linspace(1,100,50)

In [60]:
ones.std(axis=1)
#standard deviation 

array([ 0.        ,  0.        ,  0.        ,  0.        , 42.43524479])

array([ 0.        ,  0.        ,  0.        ,  0.        , 42.43524479])

In [57]:
arr

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [58]:
np.log(arr)

array([0.        , 1.10539198, 1.61756804, 1.95461848, 2.20625398,
       2.40712895, 2.57432443, 2.71752895, 2.84277136, 2.95405958,
       3.05419369, 3.14520732, 3.22862407, 3.30561506, 3.37709983,
       3.44381368, 3.50635379, 3.56521179, 3.62079725, 3.67345498,
       3.72347804, 3.77111755, 3.81659037, 3.86008503, 3.90176651,
       3.94177993, 3.98025368, 4.01730189, 4.05302641, 4.0875186 ,
       4.12086063, 4.15312675, 4.18438423, 4.21469422, 4.24411247,
       4.27268997, 4.30047343, 4.3275058 , 4.3538266 , 4.37947235,
       4.40447681, 4.42887127, 4.45268479, 4.47594438, 4.49867524,
       4.52090087, 4.54264325, 4.56392293, 4.58475921, 4.60517019])

In [63]:
np.sin(arr)

array([ 0.84147098,  0.1208881 , -0.94655078,  0.7018841 ,  0.33645069,
       -0.99433779,  0.5278595 ,  0.53550545, -0.99333794,  0.32793565,
        0.7082858 , -0.9436003 ,  0.11192174,  0.84631435, -0.84756522,
       -0.10958357,  0.94281876, -0.70994463, -0.3257122 ,  0.99306408,
       -0.53749084, -0.52585986,  0.99458504, -0.33866525, -0.70020639,
        0.94730702, -0.12322315, -0.84019752,  0.85354968,  0.09826485,
       -0.93896463,  0.71791322,  0.31493152, -0.99166176,  0.54705258,
        0.51614618, -0.99570333,  0.34935098,  0.69203629, -0.95089105,
        0.1345086 ,  0.83397187, -0.8594236 , -0.08693341,  0.9349889 ,
       -0.72578883, -0.30411005,  0.99013101, -0.55654346, -0.50636564])

In [65]:
np.abs(arr)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [66]:
np.random.rand(3)
#generates 3 random values in range of 0 to 1

array([0.26147273, 0.50863415, 0.62114337])

In [67]:
np.random.rand(4,3)

array([[0.30644494, 0.86600471, 0.45036998],
       [0.00910374, 0.96334385, 0.91630241],
       [0.7304103 , 0.32072743, 0.2739609 ],
       [0.44778624, 0.89385082, 0.54958985]])

In [68]:
np.random.rand(4,3)*10
#generating random values

array([[1.04200973, 4.39535615, 1.48235768],
       [3.13193068, 4.96227699, 1.82890405],
       [0.49732834, 7.88957853, 9.17099931],
       [4.59614229, 2.27772731, 2.19663462]])

In [69]:
np.random.randint(1,8)
#generating random integer value

2

In [72]:
np.random.seed(3)
np.random.randint(1,10,(10,15))

array([[9, 4, 9, 9, 1, 6, 4, 6, 8, 7, 1, 5, 8, 9, 2],
       [7, 3, 3, 2, 4, 6, 9, 2, 9, 8, 9, 2, 1, 6, 5],
       [2, 6, 5, 8, 7, 1, 1, 3, 5, 6, 9, 9, 8, 6, 2],
       [2, 2, 6, 6, 8, 5, 4, 1, 1, 1, 1, 3, 3, 8, 1],
       [6, 1, 2, 5, 2, 3, 3, 5, 9, 1, 7, 1, 5, 2, 6],
       [2, 9, 9, 8, 1, 1, 2, 8, 9, 8, 5, 1, 1, 5, 4],
       [1, 9, 3, 8, 3, 2, 4, 3, 5, 2, 3, 3, 8, 4, 5],
       [2, 7, 8, 2, 1, 1, 6, 9, 5, 9, 9, 4, 5, 3, 6],
       [5, 8, 2, 1, 8, 5, 9, 9, 5, 2, 5, 1, 6, 7, 8],
       [1, 8, 9, 2, 6, 4, 7, 2, 4, 8, 5, 1, 9, 5, 8]])

In [73]:
arr = np.arange(20)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
arr.min()

0

In [77]:
arr.max()

19

In [78]:
arr.argmin()

0

In [79]:
arr.argmax()

19

In [80]:
arr.sort()

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
np.random.shuffle(arr)

In [84]:
arr

array([ 9,  4, 13,  7, 18,  0, 16, 17,  2,  8,  1,  5,  3, 11, 19, 14, 15,
       12,  6, 10])